# Generated by Django 5.1.2 on 2024-10-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('num_pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('cat_num', models.PositiveSmallIntegerField()),
                ('weights', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_valid', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('time', models.DurationField()),
            ],
        ),
    ]
