# Generated by Django 5.1.2 on 2024-10-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
