# Generated by Django 5.1.2 on 2024-10-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_category_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
