# Generated by Django 5.1.2 on 2024-10-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_alter_category_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
