# Generated by Django 5.1.2 on 2024-10-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_category_updated_alter_category_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
